apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - env:
        - name: FOSSOLOGY_DB_HOST
          value: db
        - name: FOSSOLOGY_DB_NAME
          value: fossology
        - name: FOSSOLOGY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: db-secret
        - name: FOSSOLOGY_DB_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: db-secret
        image: fossology/scheduler:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - "true"
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: scheduler
        ports:
        - containerPort: 24693
        readinessProbe:
          exec:
            command:
            - "true"
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - mountPath: /srv/fossology/repository/
          name: repository
      hostname: scheduler
      restartPolicy: Always
      serviceAccountName: internal-kubectl
      subdomain: svc
      volumes:
      - name: repository
        persistentVolumeClaim:
          claimName: repository
