apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agent
    agent.type: scanoss
  name: scanoss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
      agent.type: scanoss
  strategy: {}
  template:
    metadata:
      labels:
        app: agent
        agent.type: scanoss
    spec:
      hostname: scanoss
      subdomain: agent-svc
      containers:
        - args:
            - agent
            - scanoss
          env:
            - name: FOSSOLOGY_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fossology
                  key: FOSSOLOGY_DB_HOST
            - name: FOSSOLOGY_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db
                  key: POSTGRES_DB
            - name: FOSSOLOGY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: FOSSOLOGY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: FOSSOLOGY_SCHEDULER_HOST
              valueFrom:
                configMapKeyRef:
                  name: fossology
                  key: FOSSOLOGY_SCHEDULER_HOST
          image: fossology/scanoss:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /srv/fossology/repository/
              name: repository
          name: scanoss
          resources: {}
      restartPolicy: Always
      volumes:
        - name: repository
          persistentVolumeClaim:
            claimName: repository
status: {}