# FOSSology Dockerfile
# SPDX-FileCopyrightText: 2021 Omar AbdelSamea <omarmohamed168@gmail.com>
# SPDX-License-Identifier: GPL-2.0
#
# Description: Docker container image recipe for pacakges base image

# FROM debian:buster-slim as builder
FROM debian:buster-slim AS builder
LABEL maintainer="Fossology <fossology@fossology.org>"

WORKDIR /fossology_packages/fossology

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y git ca-certificates 
        
RUN  DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget lsb-release sudo composer curl php-cli \
  && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y libcppunit-dev libcunit1-dev libcurl4-openssl-dev libjson-c-dev libdbd-sqlite3-perl \
  && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y php-sqlite3 php-zip tar debhelper libssl-dev postgresql-server-dev-all

COPY . /fossology_packages/fossology

RUN  ./utils/fo-installdeps -y -b

RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libdb-dev \
    libpq-dev \
    python3-dev \
    libgcrypt20-dev \
    libglib2.0-dev \
    debhelper

RUN  ./utils/fo-debuild --no-sign --no-tar       

ENV FOSSOLOGY_DB_HOST=db
ENV FOSSOLOGY_DB_NAME=fossology
ENV FOSSOLOGY_DB_USER=fossy
ENV FOSSOLOGY_DB_PASSWORD=fossy

FROM scratch

WORKDIR /fossology_packages/fossology

COPY --from=builder /fossology_packages/fossology/packages /fossology_packages/fossology/packages