# FOSSology Dockerfile for readmeoss agent
# SPDX-FileCopyrightText: 2025 Muhammad Salman <chsalmanramzan422@gmail.com>
# SPDX-License-Identifier: GPL-2.0

# Description: Docker container image recipe for readmeoss agent

FROM fossology/packages:latest AS builder
LABEL maintainer="Fossology <fossology@fossology.org>"

WORKDIR /fossology_packages/fossology

FROM debian:bookworm-slim

WORKDIR /fossology

LABEL maintainer="Fossology <fossology@fossology.org>"

COPY --from=builder /fossology_packages/fossology/packages/fossology-common_*_amd64.deb .
COPY --from=builder /fossology_packages/fossology/packages/fossology-readmeoss_*_amd64.deb .

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && mkdir -p /etc/fossology \
    && dpkg -i fossology-common_*_amd64.deb fossology-readmeoss_*_amd64.deb || echo "deb failed" \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y -f

COPY ./fossology.conf /etc/fossology/fossology.conf
COPY ./Docker/fo_cli /usr/share/fossology/scheduler/agent/
COPY ./Docker/fo_conf.sh /fossology/
COPY ./Docker/docker-entrypoint.k8s.sh /fossology/docker-entrypoint.sh

RUN chmod +x /fossology/docker-entrypoint.sh
ENTRYPOINT ["/fossology/docker-entrypoint.sh"]